version: '3.8'

services:
  front:
    container_name: front
    build:
      context: ./front
    ports:
      - "8080:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - back

  back:
    container_name: back
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - AIRTABLE_API_KEY=patFBUk4mJgXYsjEX.a0e1cc4e9d386d2878e7cb77af7ea78d5430426f4f9517a4e5d0948e6066ab47
      - AIRTABLE_BASE_ID=appB6WIBl7y8fNWCK
    command: npm run dev
